external_application_port: 80

datadog_app_key: "{{ datadog_app_key_vault }}"
datadog_api_key: "{{ datadog_api_key_vault }}"
datadog_site: "datadoghq.eu"
datadog_checks:
  http_check:
    init_config:

    instances:
      - name: Wiki_js
        url: http://localhost

pip_install_packages:
      - name: docker
